// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  describe('Filter: accent', function() {
    var accent;
    beforeEach(module('coloredSyntaxApp'));
    accent = {};
    beforeEach(inject(function($filter) {
      return accent = $filter('accent');
    }));
    return it('It should remove strings without accent in them"', function() {
      var filtered, options;
      options = [
        {
          label: "accent1"
        }, {
          label: "abc"
        }, {
          label: "accent2"
        }, {
          label: "sjlfs"
        }, {
          label: "accen"
        }
      ];
      filtered = accent(options);
      return expect(filtered.length).toBe(2);
    });
  });

}).call(this);
